language: rust

rust:
  - stable
  - nightly

install:
  - cargo build --all-features --tests --examples
  - >
    if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then
        cargo build --all-features --benches
    fi

script:
  - cargo test --all-features
